In [1]:
import pandas as pd
import requests

In [5]:
df = pd.read_csv(r"D:\Retail Analytics with Statistics  Power BI Project\Data\20100056-eng\Reetail Analytics Canadian data.csv")
df.head()

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Sales,Adjustments,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859481,1.1.1.1,41377009.0,NaN,NaN,NaN,0
1,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859483,1.1.1.2,50417235.0,NaN,NaN,NaN,0
2,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,81,thousands,3,v1446859482,1.1.2.1,1110045.0,NaN,NaN,NaN,0
3,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859484,1.1.2.2,1236885.0,NaN,NaN,NaN,0
4,2017-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859485,1.2.1.1,10162441.0,NaN,NaN,NaN,0

In [6]:
df.shape

(80172, 17)

In [7]:
df.columns.tolist()

['REF_DATE',
 'GEO',
 'DGUID',
 'North American Industry Classification System (NAICS)',
 'Sales',
 'Adjustments',
 'UOM',
 'UOM_ID',
 'SCALAR_FACTOR',
 'SCALAR_ID',
 'VECTOR',
 'COORDINATE',
 'VALUE',
 'STATUS',
 'SYMBOL',
 'TERMINATED',
 'DECIMALS']

In [8]:
df.head(10)

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Sales,Adjustments,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859481,1.1.1.1,41377009.0,NaN,NaN,NaN,0
1,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859483,1.1.1.2,50417235.0,NaN,NaN,NaN,0
2,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,81,thousands,3,v1446859482,1.1.2.1,1110045.0,NaN,NaN,NaN,0
3,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859484,1.1.2.2,1236885.0,NaN,NaN,NaN,0
4,2017-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859485,1.2.1.1,10162441.0,NaN,NaN,NaN,0
5,2017-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859486,1.2.1.2,13561527.0,NaN,NaN,NaN,0
6,2017-01,Canada,2021A000011124,Automobile dealers [4411],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859487,1.3.1.1,9134064.0,NaN,NaN,NaN,0
7,2017-01,Canada,2021A000011124,Automobile dealers [4411],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859488,1.3.1.2,11980440.0,NaN,NaN,NaN,0
8,2017-01,Canada,2021A000011124,New car dealers [44111],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859489,1.4.1.1,8304437.0,NaN,NaN,NaN,0
9,2017-01,Canada,2021A000011124,New car dealers [44111],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859490,1.4.1.2,11020613.0,NaN,NaN,NaN,0

In [9]:
df[['Sales', 'Adjustments', 'UOM', 'SCALAR_FACTOR']].drop_duplicates().head(20)

                     Sales          Adjustments      UOM SCALAR_FACTOR
0       Total retail sales           Unadjusted  Dollars     thousands
1       Total retail sales  Seasonally adjusted  Dollars     thousands
2  Retail e-commerce sales           Unadjusted  Dollars     thousands
3  Retail e-commerce sales  Seasonally adjusted  Dollars     thousands

In [10]:
df['GEO'].drop_duplicates()

0                             Canada
60         Newfoundland and Labrador
90              Prince Edward Island
120                      Nova Scotia
150                    New Brunswick
180                           Quebec
210                 Montréal, Quebec
240                          Ontario
270                 Toronto, Ontario
300                         Manitoba
330                     Saskatchewan
360                          Alberta
390                 British Columbia
420      Vancouver, British Columbia
450                            Yukon
480            Northwest Territories
510                          Nunavut
13262                 Quebec, Quebec
13292               Gatineau, Quebec
13384                Ottawa, Ontario
13445             Winnipeg, Manitoba
13537               Calgary, Alberta
13567              Edmonton, Alberta
Name: GEO, dtype: object

In [11]:
df['North American Industry Classification System (NAICS)'].drop_duplicates().head(30)

0                                     Retail trade [44-45]
4                    Motor vehicle and parts dealers [441]
6                                Automobile dealers [4411]
8                                  New car dealers [44111]
10                                Used car dealers [44112]
12                      Other motor vehicle dealers [4412]
14       Automotive parts, accessories and tire retaile...
16       Building material and garden equipment and sup...
18                       Food and beverage retailers [445]
20                Grocery and convenience retailers [4451]
22       Supermarkets and other grocery retailers (exce...
24       Convenience retailers and vending machine oper...
26                         Specialty food retailers [4452]
28                  Beer, wine and liquor retailers [4453]
30       Furniture, home furnishings, electronics and a...
32       Furniture, floor covering, window treatment an...
34                             Furniture retailers [44911]
36       Floor covering, window treatment and other hom...
38             Electronics and appliances retailers [4492]
40                     General merchandise retailers [455]
42                Health and personal care retailers [456]
44                Gasoline stations and fuel vendors [457]
46       Clothing, clothing accessories, shoes, jewelle...
48       Clothing and clothing accessories retailers [4...
50                                   Shoe retailers [4582]
52       Jewellery, luggage and leather goods retailers...
54       Sporting goods, hobby, musical instrument, boo...
56       Sporting goods, hobby, musical instrument, boo...
58                          Miscellaneous retailers [459B]
11400                          Cannabis retailers [459993]
Name: North American Industry Classification System (NAICS), dtype: object

In [12]:
df['REF_DATE'].min(), df['REF_DATE'].max()

('2017-01', '2026-07')

In [13]:
df['REF_DATE'].head()

0    2017-01
1    2017-01
2    2017-01
3    2017-01
4    2017-01
Name: REF_DATE, dtype: object

In [14]:
df['REF_DATE'] = pd.to_datetime(df['REF_DATE'], format='%Y-%m')

In [15]:
df['REF_DATE'].head()

0   2017-01-01
1   2017-01-01
2   2017-01-01
3   2017-01-01
4   2017-01-01
Name: REF_DATE, dtype: datetime64[ns]

In [16]:
df.isnull().sum()

REF_DATE                                                     0
GEO                                                          0
DGUID                                                        0
North American Industry Classification System (NAICS)        0
Sales                                                        0
Adjustments                                                  0
UOM                                                          0
UOM_ID                                                       0
SCALAR_FACTOR                                                0
SCALAR_ID                                                    0
VECTOR                                                       0
COORDINATE                                                   0
VALUE                                                    10398
STATUS                                                   39321
SYMBOL                                                   80172
TERMINATED                                               80172
DECIMALS                                                     0
dtype: int64

In [17]:
df[df['VALUE'].isnull()][
    ['REF_DATE', 'GEO', 'North American Industry Classification System (NAICS)',
     'Sales', 'Adjustments', 'STATUS']
].head(20)

,REF_DATE,GEO,North American Industry Classification System (NAICS),Sales,Adjustments,STATUS
68,2017-01-01,Newfoundland and Labrador,Building material and garden equipment and sup...,Total retail sales,Unadjusted,x
73,2017-01-01,Newfoundland and Labrador,Specialty food retailers [4452],Total retail sales,Unadjusted,x
74,2017-01-01,Newfoundland and Labrador,"Beer, wine and liquor retailers [4453]",Total retail sales,Unadjusted,x
75,2017-01-01,Newfoundland and Labrador,"Furniture, home furnishings, electronics and a...",Total retail sales,Unadjusted,x
76,2017-01-01,Newfoundland and Labrador,"Furniture, floor covering, window treatment an...",Total retail sales,Unadjusted,x
78,2017-01-01,Newfoundland and Labrador,"Floor covering, window treatment and other hom...",Total retail sales,Unadjusted,x
94,2017-01-01,Prince Edward Island,New car dealers [44111],Total retail sales,Unadjusted,x
95,2017-01-01,Prince Edward Island,Used car dealers [44112],Total retail sales,Unadjusted,x
103,2017-01-01,Prince Edward Island,Specialty food retailers [4452],Total retail sales,Unadjusted,x
104,2017-01-01,Prince Edward Island,"Beer, wine and liquor retailers [4453]",Total retail sales,Unadjusted,x
107,2017-01-01,Prince Edward Island,Furniture retailers [44911],Total retail sales,Unadjusted,x
108,2017-01-01,Prince Edward Island,"Floor covering, window treatment and other hom...",Total retail sales,Unadjusted,x
115,2017-01-01,Prince Edward Island,Shoe retailers [4582],Total retail sales,Unadjusted,x
116,2017-01-01,Prince Edward Island,"Jewellery, luggage and leather goods retailers...",Total retail sales,Unadjusted,x
118,2017-01-01,Prince Edward Island,"Sporting goods, hobby, musical instrument, boo...",Total retail sales,Unadjusted,x
119,2017-01-01,Prince Edward Island,Miscellaneous retailers [459B],Total retail sales,Unadjusted,x
126,2017-01-01,Nova Scotia,Other motor vehicle dealers [4412],Total retail sales,Unadjusted,F
133,2017-01-01,Nova Scotia,Specialty food retailers [4452],Total retail sales,Unadjusted,x
134,2017-01-01,Nova Scotia,"Beer, wine and liquor retailers [4453]",Total retail sales,Unadjusted,x
163,2017-01-01,New Brunswick,Specialty food retailers [4452],Total retail sales,Unadjusted,x

In [18]:
df_clean = df.dropna(subset=['VALUE'])

In [19]:
df_clean.shape

(69774, 17)

In [20]:
df_clean = df_clean[
    [
        'REF_DATE',
        'GEO',
        'North American Industry Classification System (NAICS)',
        'Sales',
        'Adjustments',
        'UOM',
        'SCALAR_FACTOR',
        'VALUE'
    ]
]

In [21]:
df_clean.head()

,REF_DATE,GEO,North American Industry Classification System (NAICS),Sales,Adjustments,UOM,SCALAR_FACTOR,VALUE
0,2017-01-01,Canada,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,thousands,41377009.0
1,2017-01-01,Canada,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,thousands,50417235.0
2,2017-01-01,Canada,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,thousands,1110045.0
3,2017-01-01,Canada,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,thousands,1236885.0
4,2017-01-01,Canada,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,thousands,10162441.0

In [22]:
df_clean.dtypes

REF_DATE                                                 datetime64[ns]
GEO                                                              object
North American Industry Classification System (NAICS)            object
Sales                                                            object
Adjustments                                                      object
UOM                                                              object
SCALAR_FACTOR                                                    object
VALUE                                                           float64
dtype: object

In [23]:
df_clean['SCALAR_FACTOR'].drop_duplicates()

0    thousands
Name: SCALAR_FACTOR, dtype: object

In [24]:
df_clean['Sales_Dollars'] = df_clean['VALUE'] * 1000

In [25]:
df_clean[['VALUE', 'Sales_Dollars']].head()

        VALUE  Sales_Dollars
0  41377009.0   4.137701e+10
1  50417235.0   5.041724e+10
2   1110045.0   1.110045e+09
3   1236885.0   1.236885e+09
4  10162441.0   1.016244e+10

In [26]:
pd.options.display.float_format = '{:,.2f}'.format

In [27]:
df_clean[['VALUE', 'Sales_Dollars']].head()

          VALUE     Sales_Dollars
0 41,377,009.00 41,377,009,000.00
1 50,417,235.00 50,417,235,000.00
2  1,110,045.00  1,110,045,000.00
3  1,236,885.00  1,236,885,000.00
4 10,162,441.00 10,162,441,000.00

In [28]:
df_clean['Sales_Dollars'].describe()

count           69,774.00
mean     1,207,380,615.85
std      4,332,719,845.92
min              1,000.00
25%         37,926,500.00
50%        165,145,000.00
75%        678,709,500.00
max     79,927,499,000.00
Name: Sales_Dollars, dtype: float64

In [29]:
monthly_sales = (
    df_clean[
        (df_clean['GEO'] == 'Canada') &
        (df_clean['Sales'] == 'Total retail sales') &
        (df_clean['Adjustments'] == 'Seasonally adjusted') &
        (df_clean['North American Industry Classification System (NAICS)'] == 'Retail trade [44-45]')
    ]
    [['REF_DATE', 'Sales_Dollars']]
    .sort_values('REF_DATE')
)

monthly_sales.head()

       REF_DATE     Sales_Dollars
1    2017-01-01 50,417,235,000.00
541  2017-02-01 49,863,452,000.00
1081 2017-03-01 49,937,420,000.00
1621 2017-04-01 50,827,438,000.00
2161 2017-05-01 50,711,634,000.00

In [30]:
monthly_sales['MoM_Growth_%'] = (
    monthly_sales['Sales_Dollars']
    .pct_change() * 100
)

monthly_sales.head()

       REF_DATE     Sales_Dollars  MoM_Growth_%
1    2017-01-01 50,417,235,000.00           NaN
541  2017-02-01 49,863,452,000.00         -1.10
1081 2017-03-01 49,937,420,000.00          0.15
1621 2017-04-01 50,827,438,000.00          1.78
2161 2017-05-01 50,711,634,000.00         -0.23

In [31]:
monthly_sales['YoY_Growth_%'] = (
    monthly_sales['Sales_Dollars']
    .pct_change(periods=12) * 100
)
monthly_sales.head(15)

       REF_DATE     Sales_Dollars  MoM_Growth_%  YoY_Growth_%
1    2017-01-01 50,417,235,000.00           NaN           NaN
541  2017-02-01 49,863,452,000.00         -1.10           NaN
1081 2017-03-01 49,937,420,000.00          0.15           NaN
1621 2017-04-01 50,827,438,000.00          1.78           NaN
2161 2017-05-01 50,711,634,000.00         -0.23           NaN
2701 2017-06-01 50,762,624,000.00          0.10           NaN
3241 2017-07-01 50,879,002,000.00          0.23           NaN
3781 2017-08-01 51,011,588,000.00          0.26           NaN
4321 2017-09-01 51,040,384,000.00          0.06           NaN
4861 2017-10-01 52,522,532,000.00          2.90           NaN
5401 2017-11-01 52,139,092,000.00         -0.73           NaN
5941 2017-12-01 52,310,573,000.00          0.33           NaN
6481 2018-01-01 52,271,446,000.00         -0.07          3.68
7021 2018-02-01 52,035,465,000.00         -0.45          4.36
7561 2018-03-01 51,946,965,000.00         -0.17          4.02

In [32]:
monthly_sales['3_Month_Moving_Avg'] = (
    monthly_sales['Sales_Dollars']
    .rolling(window=3)
    .mean()
)

monthly_sales.head(8)

,REF_DATE,Sales_Dollars,MoM_Growth_%,YoY_Growth_%,3_Month_Moving_Avg
1,2017-01-01,"50,417,235,000.00",NaN,NaN,NaN
541,2017-02-01,"49,863,452,000.00",-1.10,NaN,NaN
1081,2017-03-01,"49,937,420,000.00",0.15,NaN,"50,072,702,333.33"
1621,2017-04-01,"50,827,438,000.00",1.78,NaN,"50,209,436,666.67"
2161,2017-05-01,"50,711,634,000.00",-0.23,NaN,"50,492,164,000.00"
2701,2017-06-01,"50,762,624,000.00",0.10,NaN,"50,767,232,000.00"
3241,2017-07-01,"50,879,002,000.00",0.23,NaN,"50,784,420,000.00"
3781,2017-08-01,"51,011,588,000.00",0.26,NaN,"50,884,404,666.67"

In [33]:
monthly_sales['12_Month_Moving_Avg'] = (
    monthly_sales['Sales_Dollars']
    .rolling(window=12)
    .mean()
)

monthly_sales.head(15)

,REF_DATE,Sales_Dollars,MoM_Growth_%,YoY_Growth_%,3_Month_Moving_Avg,12_Month_Moving_Avg
1,2017-01-01,"50,417,235,000.00",NaN,NaN,NaN,NaN
541,2017-02-01,"49,863,452,000.00",-1.10,NaN,NaN,NaN
1081,2017-03-01,"49,937,420,000.00",0.15,NaN,"50,072,702,333.33",NaN
1621,2017-04-01,"50,827,438,000.00",1.78,NaN,"50,209,436,666.67",NaN
2161,2017-05-01,"50,711,634,000.00",-0.23,NaN,"50,492,164,000.00",NaN
2701,2017-06-01,"50,762,624,000.00",0.10,NaN,"50,767,232,000.00",NaN
3241,2017-07-01,"50,879,002,000.00",0.23,NaN,"50,784,420,000.00",NaN
3781,2017-08-01,"51,011,588,000.00",0.26,NaN,"50,884,404,666.67",NaN
4321,2017-09-01,"51,040,384,000.00",0.06,NaN,"50,976,991,333.33",NaN
4861,2017-10-01,"52,522,532,000.00",2.90,NaN,"51,524,834,666.67",NaN
5401,2017-11-01,"52,139,092,000.00",-0.73,NaN,"51,900,669,333.33",NaN
5941,2017-12-01,"52,310,573,000.00",0.33,NaN,"52,324,065,666.67","51,035,247,833.33"
6481,2018-01-01,"52,271,446,000.00",-0.07,3.68,"52,240,370,333.33","51,189,765,416.67"
7021,2018-02-01,"52,035,465,000.00",-0.45,4.36,"52,205,828,000.00","51,370,766,500.00"
7561,2018-03-01,"51,946,965,000.00",-0.17,4.02,"52,084,625,333.33","51,538,228,583.33"

In [34]:
monthly_sales['3_Month_Volatility_%'] = (
    monthly_sales['MoM_Growth_%']
    .rolling(window=3)
    .std()
)

monthly_sales.head(10)

,REF_DATE,Sales_Dollars,MoM_Growth_%,YoY_Growth_%,3_Month_Moving_Avg,12_Month_Moving_Avg,3_Month_Volatility_%
1,2017-01-01,"50,417,235,000.00",NaN,NaN,NaN,NaN,NaN
541,2017-02-01,"49,863,452,000.00",-1.10,NaN,NaN,NaN,NaN
1081,2017-03-01,"49,937,420,000.00",0.15,NaN,"50,072,702,333.33",NaN,NaN
1621,2017-04-01,"50,827,438,000.00",1.78,NaN,"50,209,436,666.67",NaN,1.44
2161,2017-05-01,"50,711,634,000.00",-0.23,NaN,"50,492,164,000.00",NaN,1.07
2701,2017-06-01,"50,762,624,000.00",0.10,NaN,"50,767,232,000.00",NaN,1.08
3241,2017-07-01,"50,879,002,000.00",0.23,NaN,"50,784,420,000.00",NaN,0.24
3781,2017-08-01,"51,011,588,000.00",0.26,NaN,"50,884,404,666.67",NaN,0.08
4321,2017-09-01,"51,040,384,000.00",0.06,NaN,"50,976,991,333.33",NaN,0.11
4861,2017-10-01,"52,522,532,000.00",2.90,NaN,"51,524,834,666.67",NaN,1.59

In [35]:
monthly_sales['MoM_Z_Score'] = (
    monthly_sales['MoM_Growth_%'] - monthly_sales['MoM_Growth_%'].mean()
) / monthly_sales['MoM_Growth_%'].std()

monthly_sales['Anomaly_Flag'] = (
    monthly_sales['MoM_Z_Score'].abs() >= 2
)

monthly_sales[
    ['REF_DATE', 'MoM_Growth_%', 'MoM_Z_Score', 'Anomaly_Flag']
].head(15)

       REF_DATE  MoM_Growth_%  MoM_Z_Score  Anomaly_Flag
1    2017-01-01           NaN          NaN         False
541  2017-02-01         -1.10        -0.37         False
1081 2017-03-01          0.15        -0.07         False
1621 2017-04-01          1.78         0.34         False
2161 2017-05-01         -0.23        -0.16         False
2701 2017-06-01          0.10        -0.08         False
3241 2017-07-01          0.23        -0.05         False
3781 2017-08-01          0.26        -0.04         False
4321 2017-09-01          0.06        -0.09         False
4861 2017-10-01          2.90         0.61         False
5401 2017-11-01         -0.73        -0.28         False
5941 2017-12-01          0.33        -0.02         False
6481 2018-01-01         -0.07        -0.12         False
7021 2018-02-01         -0.45        -0.21         False
7561 2018-03-01         -0.17        -0.14         False

In [36]:
import os

os.path.exists(
    r"D:\Retail Analytics with Statistics Power BI Project\Data\monthly_sales_analysis.csv"
)

False

In [37]:
monthly_sales.to_csv(
    r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv",
    index=False
)

In [38]:
import os

os.path.exists(
    r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv"
)

True

In [39]:
import requests

url = "https://www150.statcan.gc.ca/n1/en/tbl/csv/20100056-eng.zip"

zip_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\20100056-eng.zip"

response = requests.get(url)

with open(zip_path, "wb") as file:
    file.write(response.content)

print("Download complete")

Download complete

In [40]:
import zipfile
import os

extract_folder = r"D:\Retail Analytics with Statistics  Power BI Project\Data\20100056-eng"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("Extraction complete")

Extraction complete

In [43]:
import pandas as pd
import os

csv_path = os.path.join(
    extract_folder,
    "20100056-eng.csv"
)

df = pd.read_csv(csv_path)

print(df.shape)
df.head()

(80172, 17)

,REF_DATE,GEO,DGUID,North American Industry Classification System (NAICS),Sales,Adjustments,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859481,1.1.1.1,"41,377,009.00",NaN,NaN,NaN,0
1,2017-01,Canada,2021A000011124,Retail trade [44-45],Total retail sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859483,1.1.1.2,"50,417,235.00",NaN,NaN,NaN,0
2,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Unadjusted,Dollars,81,thousands,3,v1446859482,1.1.2.1,"1,110,045.00",NaN,NaN,NaN,0
3,2017-01,Canada,2021A000011124,Retail trade [44-45],Retail e-commerce sales,Seasonally adjusted,Dollars,81,thousands,3,v1446859484,1.1.2.2,"1,236,885.00",NaN,NaN,NaN,0
4,2017-01,Canada,2021A000011124,Motor vehicle and parts dealers [441],Total retail sales,Unadjusted,Dollars,81,thousands,3,v1446859485,1.2.1.1,"10,162,441.00",NaN,NaN,NaN,0

In [44]:
df['REF_DATE'] = pd.to_datetime(df['REF_DATE'], format='%Y-%m')

df_clean = df.dropna(subset=['VALUE']).copy()

df_clean = df_clean[
    [
        'REF_DATE',
        'GEO',
        'North American Industry Classification System (NAICS)',
        'Sales',
        'Adjustments',
        'UOM',
        'SCALAR_FACTOR',
        'VALUE'
    ]
]

df_clean['Sales_Dollars'] = df_clean['VALUE'] * 1000

print(df_clean.shape)

(69774, 9)

In [45]:
monthly_sales = (
    df_clean[
        (df_clean['GEO'] == 'Canada') &
        (df_clean['Sales'] == 'Total retail sales') &
        (df_clean['Adjustments'] == 'Seasonally adjusted') &
        (df_clean['North American Industry Classification System (NAICS)'] == 'Retail trade [44-45]')
    ]
    [['REF_DATE', 'Sales_Dollars']]
    .sort_values('REF_DATE')
    .copy()
)

monthly_sales['MoM_Growth_%'] = (
    monthly_sales['Sales_Dollars'].pct_change() * 100
)

monthly_sales['YoY_Growth_%'] = (
    monthly_sales['Sales_Dollars'].pct_change(periods=12) * 100
)

monthly_sales['3_Month_Moving_Avg'] = (
    monthly_sales['Sales_Dollars'].rolling(window=3).mean()
)

monthly_sales['12_Month_Moving_Avg'] = (
    monthly_sales['Sales_Dollars'].rolling(window=12).mean()
)

monthly_sales['3_Month_Volatility_%'] = (
    monthly_sales['MoM_Growth_%'].rolling(window=3).std()
)

monthly_sales['MoM_Z_Score'] = (
    monthly_sales['MoM_Growth_%'] - monthly_sales['MoM_Growth_%'].mean()
) / monthly_sales['MoM_Growth_%'].std()

monthly_sales['Anomaly_Flag'] = (
    monthly_sales['MoM_Z_Score'].abs() >= 2
)

monthly_sales.tail()

,REF_DATE,Sales_Dollars,MoM_Growth_%,YoY_Growth_%,3_Month_Moving_Avg,12_Month_Moving_Avg,3_Month_Volatility_%,MoM_Z_Score,Anomaly_Flag
76483,2026-03-01,"72,725,905,000.00",0.93,3.50,"72,143,447,333.33","70,818,027,083.33",0.38,0.13,False
77221,2026-04-01,"73,018,478,000.00",0.40,3.70,"72,599,424,333.33","71,035,119,833.33",0.27,-0.00,False
77959,2026-05-01,"73,779,725,000.00",1.04,5.99,"73,174,702,666.67","71,382,373,666.67",0.34,0.15,False
78697,2026-06-01,"74,245,528,000.00",0.63,5.19,"73,681,243,666.67","71,687,898,916.67",0.32,0.05,False
79435,2026-07-01,"73,696,547,000.00",-0.74,5.08,"73,907,266,666.67","71,984,729,833.33",0.93,-0.28,False

In [46]:
output_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv"

monthly_sales.to_csv(output_path, index=False)

print("Power BI file updated")

PermissionError: [Errno 13] Permission denied: 'D:\\Retail Analytics with Statistics  Power BI Project\\Data\\monthly_sales_analysis.csv'

In [47]:
output_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv"

monthly_sales.to_csv(output_path, index=False)

print("Power BI file updated")

PermissionError: [Errno 13] Permission denied: 'D:\\Retail Analytics with Statistics  Power BI Project\\Data\\monthly_sales_analysis.csv'

In [48]:
test_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis_test.csv"

monthly_sales.to_csv(test_path, index=False)

print("Test file created")

Test file created

In [49]:
test_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis_test.csv"

monthly_sales.to_csv(test_path, index=False)

print("Test file created")

Test file created

In [50]:
output_path = r"D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv"

monthly_sales.to_csv(output_path, index=False)

print("Power BI file updated")

Power BI file updated

In [51]:
print(output_path)

D:\Retail Analytics with Statistics  Power BI Project\Data\monthly_sales_analysis.csv

In [52]:
print(csv_path)

D:\Retail Analytics with Statistics  Power BI Project\Data\20100056-eng\20100056-eng.csv

In [53]:
print(zip_path)

D:\Retail Analytics with Statistics  Power BI Project\Data\20100056-eng.zip

In [54]:
import os
print(os.path.exists(output_path))

True

# Canadian Retail Sales Analytics

## Project Overview
Built an end-to-end retail analytics solution using Statistics Canada retail sales data, Python, and Power BI.

## Pipeline
Statistics Canada → Python download → unzip → clean → statistical analysis → CSV → Power BI refresh

## Python Analysis
- Month-over-Month Growth
- Year-over-Year Growth
- 3-Month Moving Average
- 12-Month Moving Average
- 3-Month Volatility
- Z-Score Analysis
- Anomaly Detection

## Power BI Dashboard
Includes:
- Total Sales
- Average Monthly Sales
- Latest MoM Growth %
- Latest YoY Growth %
- Latest 3M Volatility %
- Anomaly Months
- Sales trend analysis
- Growth trend analysis
- Anomaly detection
- YoY growth gauge
- Date filtering

## Tools
- Python
- Pandas
- Jupyter Notebook
- Power BI
- DAX
- Power Query
- Statistics Canada Open Data

## Data Source
Statistics Canada Monthly Retail Trade data.